### ISSUE TITLE
add a bounding box option for this layout

### ISSUE THREAD

**Issue by d2fong** [cytoscape/cytoscape.js-klay#5]
- [ ] bounding box
- [x] ready function
- [x] stop function
- [x] animate
- [x] animationDuration
- [x] animationEasing
- [x] fit
- [x] padding on fit

**Comment by d2fong** [comment]
Bounding box can possibly be implemented by passing the bb option as a property to the top level graph root

**Comment by d2fong** [comment]
Seems like a bounding box type option is not currently supported:

https://github.com/OpenKieler/klayjs/issues/14

**Comment by d2fong** [comment]
@maxkfranz eles.layoutPositions() handles most of these options  which I have added to the documentation.

The only one that doesn't seem to be supported right now is the boundingBox option.  Should we publish this extension now or wait?

**Comment by maxkfranz** [comment]
Probably best to just publish then.  We can always add more features later.  

A `boundingBox` option is mostly useful for original layouts or third-party/external-lib layouts that accept an option for it, because you really need that info internally to make it useful (e.g. for overlap avoidance and figuring out how much room you have to put other elements).  3.x supports the `spacingFactor` option, which is pretty much the same effect as `boundingBox` (when you can't use `boundingBox` internally).

**Comment by d2fong** [comment]
Okay, can I publish it or do I need to do anything special outside of the instructions in the docs?

**Comment by maxkfranz** [comment]
Should be OK to follow the readme steps

**Comment by pmackay** [comment]
I have tried some different values for `spacingFactor` and cannot see any difference in the graph layout, even with different values of `spacing`. Please could you give a bit more info on how `spacingFactor` should be used?
